lists/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),

]

superlists/urls.py
# from django.contrib import admin
# from django.urls import path
#
# urlpatterns = [
#     path('admin/', admin.site.urls),
# ]

from django.conf.urls import include, url
from lists import views as list_views
from lists import urls as list_urls

urlpatterns = [
    url(r'^$', list_views.home_page, name='home'),
    url(r'^lists/', include(list_urls)),
]

lists/models.py
from django.db import models
from django.urls import reverse

# Create your models here

class List(models.Model):

    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)


    class Meta:
        unique_together = ('list', 'text')



    def __str__(self):
        return self.text

lists/forms.py
from django import forms
from .models import Item

class ItemForm(forms.models.ModelForm):

    class Meta:

        EMPTY_ITEM_ERROR = "You can't have an empty list item"

        model = Item
        fields = ('text',)
        widgets = {
            'text': forms.fields.TextInput(attrs={
                'placeholder': 'Enter a to-do item',
            }),
        }
        error_messages = {
            'text': {'required': EMPTY_ITEM_ERROR}
        }


    def save(self, for_list, commit=True ):
        self.instance.list = for_list
        return super().save()

lists/views.py
from django.shortcuts import render, redirect
from django.utils.html import escape
from django.core.exceptions import ValidationError

from .models import Item, List
from .forms import ItemForm
# Create your views here.

def home_page(request):
    return render(request, 'home.html', {'form': ItemForm()})


def new_list(request):
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, 'home.html', {"form": form})


def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    form = ItemForm()
    if request.method == 'POST':
        form = ItemForm(data=request.POST)
        if form.is_valid():
            form.save(for_list=list_)
            return redirect(list_)
    return render(request, 'list.html', {'list': list_,'form': form })

lists/templates/home.html
<html>
    <head>
        <meta charset="UTF-8">
        <title>To-Do lists</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
        <form method="post" action="{% url 'new_list' %}">
            {{ form.text }}
        {% csrf_token %}
        {% if form.errors %}
            <div class="has-error">
                <span> {{ form.text.errors }} </span>
            </div>
        {% endif %}
        </form>

        <table id="id_list_table" >
            {% for item in items %}
            <tr>
                <td>{{ forloop.counter }}: {{ item.text }}</td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>

lists/templates/list.html
<html>
    <head>
        <meta charset="UTF-8">
        <title>To-Do lists</title>
    </head>
    <body>
        <h1>Your To-Do list</h1>
        <form method="post" action="{% url 'view_list' list.id %}">
            <input id="id_text" name="text"
                   placeholder="Enter a to-do item" />
        {% csrf_token %}
            {% if form.errors %}
            <div class="has-error">
                <span> {{ form.text.errors }} </span>
            </div>
        {% endif %}
        </form>

        <table id="id_list_table" >
            {% for item in list.item_set.all %}
            <tr>
                <td>{{ forloop.counter }}: {{ item.text }}</td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>